using System.Text.Json.Serialization;
using frontend.Models;

namespace frontend.Models
{
    [JsonSourceGenerationOptions(WriteIndented = true, PropertyNamingPolicy = JsonKnownNamingPolicy.Unspecified)]
    [JsonSerializable(typeof(User))]
    [JsonSerializable(typeof(List<User>))]
    [JsonSerializable(typeof(UserCreate))]
    [JsonSerializable(typeof(UserUpdate))]
    [JsonSerializable(typeof(Role))]
    [JsonSerializable(typeof(List<Role>))]
    [JsonSerializable(typeof(Permission))]
    [JsonSerializable(typeof(List<Permission>))]
    [JsonSerializable(typeof(RoleCreate))]
    [JsonSerializable(typeof(TokenResponse))]
    [JsonSerializable(typeof(Equipo))]
    [JsonSerializable(typeof(List<Equipo>))]
    [JsonSerializable(typeof(EquipoResponse))]
    [JsonSerializable(typeof(EquipoCreate))]
    [JsonSerializable(typeof(EquipoUpdate))]
    [JsonSerializable(typeof(Calibracion))]
    [JsonSerializable(typeof(CalibracionCreate))]
    [JsonSerializable(typeof(UploadResult))]
    [JsonSerializable(typeof(ApiError))]
    [JsonSerializable(typeof(Customer))]
    [JsonSerializable(typeof(List<Customer>))]
    [JsonSerializable(typeof(CustomerCreate))]
    [JsonSerializable(typeof(CustomerUpdate))]
    [JsonSerializable(typeof(CustomerOrder))]
    [JsonSerializable(typeof(List<CustomerOrder>))]
    [JsonSerializable(typeof(CustomerOrderItem))]
    [JsonSerializable(typeof(CustomerOrderCreate))]
    [JsonSerializable(typeof(CustomerOrderItemCreate))]
    [JsonSerializable(typeof(Quotation))]
    [JsonSerializable(typeof(List<Quotation>))]
    [JsonSerializable(typeof(QuotationCreate))]
    [JsonSerializable(typeof(QuotationItem))]
    [JsonSerializable(typeof(QuotationItemCreate))]
    [JsonSerializable(typeof(ServiceOrder))]
    [JsonSerializable(typeof(List<ServiceOrder>))]
    [JsonSerializable(typeof(ServiceOrderCreate))]
    [JsonSerializable(typeof(LabService))]
    [JsonSerializable(typeof(List<LabService>))]
    [JsonSerializable(typeof(LabServiceCreate))]
    [JsonSerializable(typeof(LabServiceUpdate))]
    [JsonSerializable(typeof(CalendarActivity))]
    [JsonSerializable(typeof(List<CalendarActivity>))]
    [JsonSerializable(typeof(CalendarActivityCreate))]
    [JsonSerializable(typeof(string[]))]
    [JsonSerializable(typeof(Dictionary<string, object>))]
    [JsonSerializable(typeof(Dictionary<string, string>))]
    public partial class AppJsonSerializerContext : JsonSerializerContext
    {
    }
}
